apache_params:
  blade_chord_m: .533
  rotor_diameter_m: 14.63
  wheel_height_m: .76196
  phase_center_offset_m: .4953
  rotor_velocity_rad_s: 29.7404
  rotor_pitch_max: -10
  rotor_pitch_min: 30
  dismount_slant_range_min: 500
  dismount_slant_range_max: 15000
  vehicle_slant_range_min: 500
  vehicle_slant_range_max: 25000
  alt_min: 30.48
  alt_max: 1524.
  az_min_bw: .866
  el_min_bw: 8.

settings:
  cpi_len: 32
  batch_sz: 128
  fc: 10000000000.
  bandwidth: 400000000.
  stft_win_sz: 256
  plp: .5
  n_ants: 2
  fft_len: 8192

generate_data_settings:
  iterations: 10
  use_local_storage: True
  save_files: True
  local_path: ./data
  obj_path: /home/jeff/Documents/target_meshes
  save_as_target: True
  save_as_clutter: True
    
# This is for setting up training of target embedding
target_exp_params:
  LR: 0.0000014
  weight_decay: 0.01
  scheduler_gamma: 0.7
  betas: [ .9, .99 ]
  step_size: 1
  swa_start: .7
  log_epoch: 10
  save_model: True
  transform_data: False
  warm_start: True
  loss_landscape: False
  output_images: False
  model_type: TargetEncoder
  patience: 550
  is_tuning: False
  max_epochs: 200
  is_training: True
  dataset_params:
    data_path: ./data/target_tensors
    train_batch_size: 50
    val_batch_size: 50
    num_workers: 0
    pin_memory: False
    split: .7
    single_example: False
    # These values are taken from a sampling of data
    mu: 0.
    var: 1.
    noise_level: 0.
  model_params:
    in_channels: 2
    latent_dim: 1024
    channel_sz: 64
    label_sz: 25
    # These values are taken from a sampling of data, should be the same as the dataset params
    mu: 0.
    var: 1.

# This is for setting up training of pulse classifier
pulse_exp_params:
  LR: 0.0014
  weight_decay: 0.1
  scheduler_gamma: 0.7
  betas: [ .9, .99 ]
  step_size: 1
  swa_start: .7
  log_epoch: 10
  save_model: True
  transform_data: False
  warm_start: False
  loss_landscape: False
  output_images: False
  model_type: PulseClassifier
  patience: 550
  is_tuning: False
  max_epochs: 5
  is_training: True
  dataset_params:
    data_path: ./data/target_tensors
    train_batch_size: 50
    val_batch_size: 50
    num_workers: 0
    pin_memory: False
    split: .7
    single_example: False
    # These values are taken from a sampling of data
    mu: 0.
    var: 1.
    noise_level: 0.
  model_params:
    in_channels: 2
    latent_dim: 1024
    channel_sz: 32
    label_sz: 25
    # These values are taken from a sampling of data, should be the same as the dataset params
    mu: 0.
    var: 1.

# For training of wavemodel
wave_exp_params:
  LR: 0.001
  weight_decay: 0.5
  scheduler_gamma: 0.7
  swa_start: .6
  warm_start: True
  betas: [.9, .99]
  step_size: 1
  log_epoch: 10
  is_tuning: False
  save_model: True
  loss_landscape: False
  patience: 5
  encoder_start_channel_sz: 2
  encoder_layers: 2
  embedding_concatenation_channels: 256
  clutter_target_channels: 256
  flowthrough_channels: 256
  decoder_layers: 2
  exp_to_ant_channels: 256
  clutter_latent_size: 512
  bandwidth: 400000000.
  max_epochs: 28
  init_task: False
  exp_name: wavemodel-6x6-goodsidelobes
  dataset_params:
    data_path: ./data
    train_batch_size: 2
    val_batch_size: 2
    num_workers: 0
    pin_memory: False
    split: .7
    single_example: False
    # These values are taken from a sampling of data
    mu: 199926611.3141519
    var: 52500339516.69853
    noise_level: 0.
    collate: True

train_params:
  log_dir: ./logs
