apache_params:
  blade_chord_m: .533
  rotor_diameter_m: 14.63
  wheel_height_m: 2.4384
  rotor_velocity_rad_s: 29.7404

perf_params:
  dismount_slant_range_min: 500
  dismount_slant_range_max: 15000
  vehicle_slant_range_min: 500
  vehicle_slant_range_max: 25000
  alt_min: 30.48
  alt_max: 1524.
  az_min_bw: .0130899
  el_min_bw: .034906

settings:
  cpi_len: 32
  batch_sz: 128
  fc: 10000000000.
  bandwidth: 400000000.
  plp: .5

generate_data_settings:
  iterations: 20
  fft_sz: 4096
  run_clutter: True
  run_targets: False

dataset_params:
  data_path: ./data
  train_batch_size: 64
  val_batch_size: 64
  num_workers: 0
  pin_memory: True
  train_split: .2
  val_split: .1

exp_params:
  LR: 0.005
  weight_decay: 0.0
  scheduler_gamma: 0.95
  kld_weight: 0.00025
  log_epoch: 10
  output_images: False

model_params:
  in_channels: 2
  latent_dim: 64
  loss_type: 'B'
  gamma: 10.0
  max_capacity: 25
  capacity_max_iter: 10000
  reg_weight: 5000  # MMD weight
  kernel_type: 'rbf'
  alpha: -9.0     # KLD weight
  beta: 10.5      # Reconstruction weight

train_params:
  log_dir: ./logs
  max_epochs: 10